### ISSUE TITLE
Implement GitHub OAuth

### ISSUE THREAD

**Issue by peikk0** [M6Web/GithubTeamReviewer#17]
It would be nice to implement GitHub OAuth to avoid sharing a token to everyone (which is a very bad practice, tokens should be treated like passwords), and allow users to see PRs on their private repositories (and only theirs).

**Comment by mikaelrandy** [comment]
:+1:

**Comment by oltodo** [comment]
I think is done now, right ?

**Comment by peikk0** [comment]
:+1:
